version: '3.4'

services:
  did-node:
    image: dirmich/hm-did-node:latest
    container_name: did-node
    build:
      context: .
      dockerfile: ./Dockerfile
    # command: 'bash -c ''./scripts/start_node.sh 1; && sleep 10; ./scripts/start_webserver.sh;'''
    command: './scripts/start_node.sh 1'
    command: './scripts/start_webserver.sh'
    networks:
      - did-network
    ports:
      - 3001:3001
      - 3002:3002
      - ${WEB_SERVER_HOST_PORT:-9000}:8000
    environment:
      - IP=${IP}
      - IPS=${IPS}
      - NODE_PORT=3001
      - DOCKERHOST=${DOCKERHOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - RUST_LOG=${RUST_LOG}
      - GENESIS_URL=${GENESIS_URL}
      - ANONYMOUS=${ANONYMOUS}
      - LEDGER_SEED=${LEDGER_SEED}
      - LEDGER_CACHE_PATH=${LEDGER_CACHE_PATH}
      - MAX_FETCH=${MAX_FETCH:-50000}
      - RESYNC_TIME=${RESYNC_TIME:-120}
      - REGISTER_NEW_DIDS=${REGISTER_NEW_DIDS:-True}
      - LEDGER_INSTANCE_NAME=${LEDGER_INSTANCE_NAME:-localhost}
      - WEB_ANALYTICS_SCRIPT=${WEB_ANALYTICS_SCRIPT}
      - INFO_SITE_TEXT=${INFO_SITE_TEXT}
      - INFO_SITE_URL=${INFO_SITE_URL}
    volumes:
      # - ledger:/home/indy/ledger
      - ./ledger:/home/indy/ledger:rw
      - ./config:/home/indy/config
      - ./server:/home/indy/server
      - webserver-cli:/home/indy/.indy-cli
      # - webserver-ledger:/home/indy/ledger
networks:
  did-network:

volumes:
  webserver-cli:
  # ledger:
  #   driver: local
  #   driver_opts:
  #     o: bind
  #     type: none
  #     device: ./ledger