version: '3'

services:
  webhook:
    container_name: server
    # image: server
    image: dirmich/webhook:latest
    restart: always
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
#     networks:
#       - backend
# networks:
#   backend:
#     external: true